#!/usr/bin/env bash

# Display header
printf "%-15s %-10s %-10s %-10s %-10s %-10s %s\n" "USER" "PID" "%CPU" "%MEM" "VSZ" "RSS" "TTY COMMAND"

# Get processes information
ps aux --forest | awk '{printf "%-15s %-10s %-10s %-10s %-10s %-10s %s\n", $1, $2, $3, $4, $5, $6, $7}'
